# Generated by Django 5.0.6 on 2024-06-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('EI', '외향형 (E) vs. 내향형 (I)'), ('SN', '감각형 (S) vs. 직관형 (N)'), ('TF', '사고형 (T) vs. 감정형 (F)'), ('JP', '판단형 (J) vs. 인식형 (P)')], max_length=2)),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
    ]
